{% set version = "2.0.4" %}

package:
  name: sdl2_mixer
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL_mixer/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 5605b6f230717acf6d09549671f7fe03f006700c61a61b86042888f81792e2b3

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("sdl2_mixer", max_pin='x') }}

requirements:
  build:
    - pkg-config  # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sdl2 2.0.*
    - smpeg2 2.0.*
    - libogg
    - libvorbis
    - libflac
    - libmad

  run:
    - sdl2 2.0.*
    - smpeg2 2.0.*

test:
  commands:
    - test -f $PREFIX/lib/libSDL2_mixer.a  # [unix]
    - test -f $PREFIX/lib/libSDL2_mixer.dylib  # [osx]
    - test -f $PREFIX/lib/libSDL2_mixer.so  # [linux]
    - test -f $PREFIX/include/SDL2/SDL_mixer.h  # [unix]
    - if not exist %LIBRARY_LIB%\\SDL2_mixer.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\SDL2_mixer.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\SDL2\\SDL_mixer.h exit 1  # [win]

about:
  home: https://www.libsdl.org/projects/SDL_mixer/
  license: Zlib
  license_file: COPYING.txt
  summary: "Sample multi-channel audio mixer library"
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://www.libsdl.org/projects/SDL_mixer/docs/index.html
  dev_url: https://github.com/libsdl-org/SDL_mixer

extra:
  recipe-maintainers:
    - dschreij
    - matham
    - h-vetinari
