{% set version = "2.8.0" %}

package:
  name: sdl2_mixer
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL_mixer/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 1146f00815c8ad22c3d48fbe31ae23dc5997936ebf30b4b3aeab6eab7ea1db3e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("sdl2_mixer", max_pin='x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - sdl2
    - fluidsynth    # [not win]
    - libflac
    - libmad
    - libogg
    - libvorbis
    - mpg123
    - opusfile      # [not win]

test:
  commands:
    # shared libraries
    - test -f $PREFIX/lib/libSDL2_mixer.so                # [linux]
    - test -f $PREFIX/lib/libSDL2_mixer.dylib             # [osx]
    - if not exist %LIBRARY_LIB%\SDL2_mixer.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\SDL2_mixer.dll exit 1    # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libSDL2_mixer.a               # [unix]

    # headers
    - test -f $PREFIX/include/SDL2/SDL_mixer.h            # [unix]
    - if not exist %LIBRARY_INC%\SDL2\SDL_mixer.h exit 1  # [win]

about:
  home: https://www.libsdl.org/projects/SDL_mixer/
  license: Zlib
  license_file: LICENSE.txt
  summary: Sample multi-channel audio mixer library
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://www.libsdl.org/projects/SDL_mixer/docs/index.html
  dev_url: https://github.com/libsdl-org/SDL_mixer

extra:
  recipe-maintainers:
    - dschreij
    - matham
    - h-vetinari
