travis:
  secure:
    BINSTAR_TOKEN: E+erIy7kTuhBO0HNkjTfle4JyiPRrtRZVeNWB/j2odBaZYNnS8ct6rk7KLEjJeZkIe0roKa0mh4Py5oWnSJf9N0ZNT8OthzmdNWGw8WfuHT4tGxmxpU8arWLS2YjSY9w3V2cQOT7VRssvUBDxIC4oZF6vui3d9/NC9+NPdwCWL+OOXQHMR21xgwtKA+gqjefT8AHEMkQ+NvXCM9nfh7JccA5cCRdavZgrTK1C7DauZMjXPGDXixS4DnSMqf1qgu4NN8aLtARsMIbo2bdG8QoxIy0zP/y6PhtypR841s06x+qYZq2WTQMWvQtDsBXZxZQ8DLYTFIuhkz9pG2rwyw7r74+dtCp8gbLY5LYidfbz3t9peqfkyfVC6u1Mh1V9ACrTSi6F6NkfeMBFohSE10Wd9xPlIPUiBEet5L0njD8DVuqE5+XR8yY/P6DmLCorgAT6xt3xayNwmG8kV35W/VkPaKH3wgz5SK4vVVJHeaz7IXoa5W3AfZbbM3Y+tsK5S4VyT3vq07JrK6Vwlit1Ag8ydfCC8i4H4FEkRhSjd3oKay8YZEyHekViWPpciuEX0Wj+sjZShdo+Y/kL0oe91/QyBJdUoFejlFWYpHYqzcch2p63hbTLXDUM4fYgrwdpA4wLN2GDSY7/2GFk1xgejyMIOPV3r81uiLHuMTZQyicNtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
