travis:
  secure:
    BINSTAR_TOKEN: 4wusaQiFHejHPmKzYAEL+8cW0XL73M/toJscBpKq/KjQk1IBCtNBz/kD4ecws/7oFIBwHx6AylK3Eg5Q3Uu3gQ7DcFk3hR+Ee1fkEcR9VFo00qkBRjg8JVVaplokXEdr0TI2aRvzQt9ccWHZxJ/f6WpUutH0Mp/jL4D1NsXSJtOjFq9hQY77yIM7DY0K8WQs1V/YjQEWLPAAi1mJvx20/+4z9qMvixtvC3hPU6P7PdzlWQAT3T4eT62DYE7fLbN7+u5dpdaM69ZlHSntv3DtlXXbKPGqPqtjke0lt+y5V3dBAR6jRAGMEOgpUs1hseiOv6WOnQ6vqcz0PShgWRrp4tsZb4yR4XAD0DJCgB9WhBFuRbIKfHlQzHUaPb64Z1GLZBMI7QIuiOY7wQnSnQ37+l5f0Eqkal78DGAyRBzbkZYR94TH0b62Gb2GRliCksVt8yi56bxxvrc9bNL9ky1/LXIR9rs/BVb/K74CMMxqplIdlrT/+OIF6mePYzaHLtnWUJTF4okwexJdmODzqZHB6SRQIFyY3rdltAf/aDEJeLPvwtTzU8XNN5KccnbC6k8QgrHt2MjAirVqBn459ET0pGCjlZx33WD9jaslhcImsIh0ZHbFY5DcULe4EEy3Bl+7ia+IdVLfih3mcIgut70cPTBpPDMSJ4PPTZz80cnRK7I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
